
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from CryptPyGui import *

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("835x534")
window.configure(bg = "#1F1F1F")


canvas = Canvas(
    window,
    bg = "#1F1F1F",
    height = 534,
    width = 835,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    131.99999999999994,
    11.0,
    anchor="nw",
    text="CryptPy",
    fill="#1CBA48",
    font=("asciid", 96 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: generateKey(),
    relief="flat"
)
button_1.place(
    x=296.99999999999994,
    y=149.0,
    width=242.0,
    height=77.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: encrypt(),
    relief="flat"
)
button_2.place(
    x=296.99999999999994,
    y=267.0,
    width=242.0,
    height=77.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: decrypt(),
    relief="flat"
)
button_3.place(
    x=296.99999999999994,
    y=385.0,
    width=242.0,
    height=77.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: exit(),
    relief="flat"
)
button_4.place(
    x=703.0,
    y=480.0,
    width=121.0,
    height=39.0
)
window.resizable(False, False)
window.mainloop()
